name: router_core
description: A decoupled navigation package for Flutter with GoRouter and exit confirmation.
version: 0.3.1

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^14.2.0

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Immutable Entities
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # Code Generation
  build_runner: ^2.4.9
  freezed: ^2.5.2
  riverpod_generator: ^2.4.0

  # Testing
  mocktail: ^1.0.3

flutter:
