name: notifications_core
description: "A Flutter package for cross-platform push notifications with multi-provider support and Riverpod integration."
version: 0.1.0
homepage:

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.1.0
  meta: ^1.11.0
  # Optional: Only needed if using FirebaseNotificationDatasource
  firebase_messaging: ^16.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter:
